version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: valorant_api
      MYSQL_ROOT_PASSWORD: avatim123
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql

  app:
    build: .
    container_name: springboot
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/valorant_api
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: avatim123
    depends_on:
      - mysql
    networks:
      - springboot-mysql
    volumes:
      - app-data:/app/uploads

volumes:
  mysql-data:
  app-data:

networks:
  springboot-mysql:
    driver: bridge